---
- name: concourse worker systemd service file
  template: src=concourse-worker.conf.j2 dest=/etc/init/concourse-worker.conf
  notify:
    - restart concourse-worker

- name: update linux kernel to 3.19
  apt: name=linux-generic-lts-vivid state=latest update_cache=yes

- name: register running kernel version
  command: uname -r
  register: running_kernel
  changed_when: false

- name: register installed kernel version
  shell: dpkg -l | grep "linux-image-[0-9]" | sort | tail -1 | perl -ane 'print substr($F[1], 12), "\n"'
  register: installed_kernel
  changed_when: false

- name: restart machine if kernel version changed
  shell: sleep 2 && shutdown -r now "Kernel update reboot triggered"
  async: 0
  poll: 0
  sudo: true
  ignore_errors: true
  register: reboot_result
  when: installed_kernel.stdout != running_kernel.stdout

- name: waiting for server to come back
  local_action: wait_for
                host={{ ansible_ssh_host | default(inventory_hostname) }}
                state=started
                port={{ansible_ssh_port | default(22, True)}}
                delay=30
                timeout=300
                connect_timeout=15
  sudo: false
  when: reboot_result|changed        
