---
- name: install postgresql
  apt: name=postgresql state=present update_cache=yes
- name: create postgresql cluster
  command: pg_createcluster 9.3 main --start creates=/etc/postgresql/9.3/main/pg_hba.conf
  environment:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
- name: install python-psycopg2 module
  apt: name=python-psycopg2 state=present
- service: name=postgresql state=started enabled=yes
- postgresql_db: name=atc
  become: true
  become_user: postgres
- postgresql_user: db=atc name=concourse priv=ALL
  become: true
  become_user: postgres
- name: overwrite postgres pg_hba.conf
  copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf mode=0600 owner=postgres group=postgres
  notify:
    - restart-postgresql
